# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c5314c6bedbfb0952fa5f4fd135298c23697947acf16e63febb31c260977675f0104a0f965f7fa1a9ace5359101020d9bdc61cea2969e5a3b2ff9788c8f0f5

test:
  secret_key_base: b69e97d389288a1c9ad788de68f612fd6360b2b775d21f75232e8ea5da8880ea5ad5da5bda50c405319a54590a91d5bd70cdfaecc4d34a436299d62af52549c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
